### ISSUE TITLE
Four of the same jobs are highlighted

### ISSUE THREAD

**Issue by joelian802** [http-quork-net/web#11]
Why is the same jobs listed multiple times and highlighted? I can click on the third listed job and it highlights the first 4 of the same job. 
Replication:
- Search for Software Developer in San Francisco, CA
- Four of the same job is listed and all four are highlighted 
![image](https://github.com/http-quork-net/web/assets/117697528/6d62f15a-4c1b-4c29-b121-bbae4f086814)

Additionally, when clicking on Apply Now, this job is no longer accepting applications.

**Comment by superjimillan** [comment]
done
