### ISSUE TITLE
Critical bug: Need a validation which disallows user to search for a location without a job title.

### ISSUE THREAD

**Issue by joelian802** [http-quork-net/web#2]
Entered a location in the job search and got this error. When I exit hit the x to exit this error, it constantly reappears. At this point I had to re-enter the website address to get to the home page. 

![image](https://github.com/http-quork-net/web/assets/117697528/d6f7713b-ea3a-494f-afd5-2326b4ee52b2)

**Comment by superjimillan** [comment]
done
